:DISKMGR_START
@ECHO OFF&&Reg.exe query "HKU\S-1-5-19\Environment">NUL
IF NOT %ERRORLEVEL% EQU 0 ECHO Right-Click ^& Run As Administrator&&PAUSE&&EXIT 0
CLS&&TITLE  Download from github.com/joshuacline&&COLOR 0B&&CALL:PAD_LINE&&ECHO                    Josh's Disk-Part Command-Wrapper&&CALL:PAD_LINE&&ECHO       WHOA^! THERE MATEY BE CAREFUL, THERE'S NO BRAKES ON THIS.
IF NOT DEFINED PROG_OPER CALL:DISK_QUERY&&ECHO  [DISK]  {I}nspect  {E}rase-Disk  {#}Change Disk-ID  {U}SB-Unplug&&CALL:PAD_LINE&&ECHO  [PARTITION]  {C}reate  {D}elete  {F}ormat  {M}ount/Unmount  {L}ock&&CALL:PAD_LINE
ECHO                 Press (Enter) to Return to Previous Menu&&CALL SET "PROMPT_SET=SELECT"&&CALL:PROMPT_SET&&IF DEFINED PROG_OPER CALL:FILE_LIST>NUL
IF DEFINED PROG_OPER IF NOT DEFINED SELECT SET PROG_OPER=
IF "%SELECT%"=="#" SET PROG_OPER=DISKMGR_CHANGEID
IF "%SELECT%"=="C" SET PROG_OPER=DISKMGR_CREATE
IF "%SELECT%"=="D" SET PROG_OPER=DISKMGR_DELETE
IF "%SELECT%"=="F" SET PROG_OPER=DISKMGR_FORMAT
IF "%SELECT%"=="L" SET PROG_OPER=DISKMGR_LOCK
IF "%SELECT%"=="U" SET PROG_OPER=DISKMGR_USBPLUG
IF "%SELECT%"=="I" SET PROG_OPER=DISKMGR_INSPECT
IF "%SELECT%"=="M" SET PROG_OPER=DISKMGR_MOUNT
IF "%SELECT%"=="E" SET PROG_OPER=DISKMGR_ERASE
IF "%PROG_OPER%"=="DISKMGR_USBPLUG" RunDll32.exe shell32.dll,Control_RunDLL hotplug.dll&&SET PROG_OPER=
IF DEFINED PROG_OPER CLS&&CALL:PAD_LINE&&ECHO                            [%PROG_OPER%]&&CALL:DISK_QUERY
IF "%PROG_OPER%"=="DISKMGR_CREATE" ECHO                            Which Disk {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_NUMBER"&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="DISKMGR_CREATE" IF DEFINED DISK_NUMBER CALL:PAD_LINE&&ECHO                        Partition Size in MB?&&CALL:PAD_LINE&&ECHO (Enter) To Use All Available Free Space&&CALL SET "PROMPT_SET=PART_SIZE"&&CALL:PROMPT_SET&&CALL:DISKMGR_CREATE
IF "%PROG_OPER%"=="DISKMGR_CHANGEID" ECHO    $HAZZAM BOOT-DRIVES STORE THE DISK-ID TO MOUNT IN WINPE&&ECHO.      CHANGING THIS WILL BREAK THE HOME-DRIVE DETECTION&&CALL:PAD_LINE&&ECHO.                             Which Disk {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_NUMBER"&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="DISKMGR_CHANGEID" IF DEFINED DISK_NUMBER CALL:PAD_LINE&&ECHO                          NEW DISK-ID?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=GET_DISK_ID"&&CALL:PROMPT_SET&&CALL:DISKMGR_CHANGEID
IF "%PROG_OPER%"=="DISKMGR_FORMAT" ECHO                            Which Disk {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_NUMBER"&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="DISKMGR_FORMAT" IF DEFINED DISK_NUMBER CALL:PAD_LINE&&ECHO                          Which Partition {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=PART_NUMBER"&&CALL:PROMPT_SET&&CALL:DISKMGR_FORMAT
IF "%PROG_OPER%"=="DISKMGR_DELETE" ECHO                            Which Disk {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_NUMBER"&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="DISKMGR_DELETE" IF DEFINED DISK_NUMBER CALL:PAD_LINE&&ECHO                          Which Partition {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=PART_NUMBER"&&CALL:PROMPT_SET&&CALL:DISKMGR_DELETE
IF "%PROG_OPER%"=="DISKMGR_INSPECT" ECHO                            Which Disk {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_NUMBER"&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="DISKMGR_INSPECT" IF DEFINED DISK_NUMBER CLS&&CALL:DISKMGR_INSPECT
IF "%PROG_OPER%"=="DISKMGR_LOCK" ECHO                            Which Disk {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_NUMBER"&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="DISKMGR_LOCK" IF DEFINED DISK_NUMBER CALL:PAD_LINE&&ECHO Which Partition {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=PART_NUMBER"&&CALL:PROMPT_SET&&CALL:DISKMGR_LOCK
IF "%PROG_OPER%"=="DISKMGR_MOUNT" ECHO                          Which Drive Letter?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_LETTER"&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="DISKMGR_MOUNT" IF EXIST "%DISK_LETTER%:\" CALL:DISKMGR_UNMOUNT&&SET PROG_OPER=&&PAUSE
IF "%PROG_OPER%"=="DISKMGR_MOUNT" IF NOT EXIST "%DISK_LETTER%:\" CALL:PAD_LINE&&ECHO                            Which Disk {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_NUMBER"&&CALL:PROMPT_SET
IF "%PROG_OPER%"=="DISKMGR_MOUNT" IF DEFINED DISK_NUMBER IF NOT EXIST "%DISK_LETTER%:\" CALL:PAD_LINE&&ECHO                          Which Partition {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=PART_NUMBER"&&CALL:PROMPT_SET&&CALL:DISKMGR_MOUNT
IF "%PROG_OPER%"=="DISKMGR_ERASE" ECHO                         Which Disk {#}?&&CALL:PAD_LINE&&CALL SET "PROMPT_SET=DISK_NUMBER"&&CALL:PROMPT_SET&&CALL:DISKMGR_ERASE
IF DEFINED PROG_OPER SET PROG_OPER=&&CALL:PAD_LINE&&ECHO	                      End of Disk-Part Operation&&CALL:PAD_LINE&&PAUSE&&DEL /Q /F "%TEMP%\DISK_PART">NUL 2>&1
GOTO:DISKMGR_START
:DISKMGR_ERASE
FOR %%a in (0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15) DO (IF "%DISK_NUMBER%"=="%%a" CALL SET "GET_DISK_ID=%%DISKID_%%a%%")
(ECHO.select disk %DISK_NUMBER%&&ECHO.clean&&ECHO.convert gpt&&ECHO.select partition 1&&ECHO.delete partition override&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART">NUL
CALL:DISKMGR_CHANGEID>NUL
ECHO All partitions on Disk %DISK_NUMBER% have been erased.&&ECHO 
EXIT /B
:DISKMGR_INSPECT
(ECHO.select disk %DISK_NUMBER%&&ECHO.detail disk&&ECHO.list partition&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART"&&ECHO 
EXIT /B
:DISKMGR_MOUNT
(ECHO.select disk %DISK_NUMBER%&&ECHO.select partition %PART_NUMBER%&&ECHO.Assign letter=%DISK_LETTER% noerr&&ECHO.Exit)>"%TEMP%\DISK_PART"&&Diskpart /s "%TEMP%\DISK_PART">NUL 2>&1
IF NOT EXIST "%DISK_LETTER%:\" (ECHO.select disk %DISK_NUMBER%&&ECHO.select partition %PART_NUMBER%&&ECHO.gpt attributes=0x8000000000000000&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART">NUL 2>&1
IF NOT EXIST "%DISK_LETTER%:\" (ECHO.select disk %DISK_NUMBER%&&ECHO.select partition %PART_NUMBER%&&ECHO.Assign letter=%DISK_LETTER% noerr&&ECHO.Exit)>"%TEMP%\DISK_PART"&&Diskpart /s "%TEMP%\DISK_PART">NUL 2>&1
EXIT /B
:DISKMGR_UNMOUNT
(ECHO.select VOLUME %DISK_LETTER%&&ECHO.Remove letter=%DISK_LETTER% noerr&&ECHO.Exit)>"%TEMP%\DISK_PART"&&Diskpart /s "%TEMP%\DISK_PART"&&ECHO 
EXIT /B
:DISKMGR_CREATE
IF NOT DEFINED PART_SIZE (ECHO.select disk %DISK_NUMBER%&&ECHO.create partition primary&&ECHO.format quick fs=ntfs&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART"&&ECHO 
IF DEFINED PART_SIZE (ECHO.select disk %DISK_NUMBER%&&ECHO.create partition primary size=%PART_SIZE%&&ECHO.format quick fs=ntfs&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART"&&ECHO 
EXIT /B
:DISKMGR_DELETE
(ECHO.select disk %DISK_NUMBER%&&ECHO.select partition %PART_NUMBER%&&ECHO.delete partition override&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART"&&ECHO 
EXIT /B
:DISKMGR_CHANGEID
(ECHO.select disk %DISK_NUMBER%&&ECHO.uniqueid disk id=%GET_DISK_ID%&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART"&&ECHO 
EXIT /B
:DISKMGR_FORMAT
(ECHO.select disk %DISK_NUMBER%&&ECHO.select partition %PART_NUMBER%&&ECHO.format quick fs=ntfs override&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART"&&ECHO 
EXIT /B
:DISKMGR_LOCK
(ECHO.select disk %DISK_NUMBER%&&ECHO.select partition %PART_NUMBER%&&ECHO.gpt attributes=0x4000000000000001&&ECHO.Exit)>"%TEMP%\DISK_PART"&&DISKPART /s "%TEMP%\DISK_PART"&&ECHO 
EXIT /B
:DISK_MENU
CLS&&ECHO        WHOA^! THERE MATEY BE CAREFUL, THERE'S NO BRAKES ON THIS.&&CALL:DISK_QUERY&&SET DISK_MENU_LBL=Target&&IF DEFINED PROG_OPER SET DISK_MENU_LBL=%PROG_OPER%&&ECHO                        Which Disk {#} To %DISK_MENU_LBL%?&&CALL:PAD_LINE&&ECHO               Press (Enter) to Return to Previous Menu&&IF DEFINED DISK_NUMBER SET DISK_NUMBER_CUR=%DISK_NUMBER%&&SET DISK_TARGET=&SET SELECT=&&SET /P "SELECT=$>>"
IF NOT DEFINED SELECT EXIT /B
FOR %%a in (0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15) DO (IF "%SELECT%"=="%%a" CALL SET DISK_TARGET=%%DISKID_%%a%%&&CALL SET DISK_TYPE=%%DISKTYPE_%%a%%)
FOR %%G in (00000000-0000-0000-0000-000000000000 0000-0000 00000000) DO (IF "%DISK_TARGET%"=="%%G" GOTO:DISK_MENU)
IF "%DISK_TARGET%"=="" GOTO:DISK_MENU
CALL:DISK_QUERY>NUL
IF NOT DEFINED DISK_NUMBER GOTO:DISK_MENU
EXIT /B
:DISK_QUERY
(ECHO.LIST DISK&&ECHO.Exit)>%TEMP%\DPQUERY1&&DISKPART /s %TEMP%\DPQUERY1>%TEMP%\DPQUERY2
FOR /F "tokens=2,4 skip=8 delims= " %%a in (%TEMP%\DPQUERY2) DO ((ECHO.SELECT DISK %%a&&ECHO.DETAIL DISK&&ECHO.Exit)>%TEMP%\DPQUERY3&&DISKPART /s %TEMP%\DPQUERY3>%TEMP%\DPQUERY4
IF NOT "%%a"=="DiskPart..." FOR /F "tokens=1-5 skip=7 delims={}: " %%1 in (%TEMP%\DPQUERY4) DO (IF "%%1"=="Type" IF "%%2"=="File" SET VSKIP%%a=%%a))
FOR /F "tokens=2,4 skip=8 delims= " %%a in (%TEMP%\DPQUERY2) DO (SET DISK%%a=&&SET DISKVENDOR_%%a=
IF NOT DEFINED VSKIP%%a (ECHO.SELECT DISK %%a&&ECHO.DETAIL DISK&&ECHO.LIST PARTITION&&ECHO.Exit)>%TEMP%\DPQUERY3&&DISKPART /s %TEMP%\DPQUERY3>%TEMP%\DPQUERY4&&SET PAD_SIZE=4&&CALL:PAD_LINE
IF NOT DEFINED VSKIP%%a IF NOT "%%a"=="DiskPart..." FOR /F "tokens=1-9 skip=7 delims={}: " %%1 in (%TEMP%\DPQUERY4) DO (
IF NOT DEFINED DISK%%a SET DISK%%a=%%a&&ECHO  DISK ^{%%a^}
IF NOT DEFINED DISKVENDOR_%%a SET DISKVENDOR_%%a=%%1 %%2 %%3&&ECHO VENDOR = %%1 %%2 %%3
IF "%%1"=="Type" SET "DISKTYPE_%%a=%%2"&&ECHO  Type  = %%2
IF "%%1 %%2"=="Disk ID" SET "DISKID_%%a=%%3"&&ECHO  UID   = %%3&&IF "%%3"=="%DISK_TARGET%" SET DISK_NUMBER=%%a
IF "%%1 %%2 %%3"=="Pagefile Disk Yes" ECHO *Active Pagefile*
IF "%%1"=="Partition" IF NOT "%%2"=="###" ECHO  {%%1 %%2}&&ECHO  Size  = %%4 %%5
IF "%%3"=="S" SET "CURRENT_HOME=%%2"))
CALL:PAD_LINE&DEL /Q /F "%TEMP%\DPQUERY*">NUL 2>&1
EXIT /B
:PAD_LINE
ECHO ====================================================================
EXIT /B
:PROMPT_SET
ECHO.&&SET PROMPT_VAR=&&SET /P "PROMPT_VAR=$>>"&&FOR %%G in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) DO (CALL SET "PROMPT_VAR=%%PROMPT_VAR:%%G=%%G%%")
CALL SET "%PROMPT_SET%=%PROMPT_VAR%"&&SET PROMPT_SET=&&SET PROMPT_VAR=
EXIT /B